"""Fixed constants for OpenROAD MCP server."""

# System exit codes
EXIT_CODE_KEYBOARD_INTERRUPT = 130
EXIT_CODE_SUCCESS = 0
EXIT_CODE_ERROR = 1

# Context display limits
RECENT_OUTPUT_LINES = 20
LAST_COMMANDS_COUNT = 5

# Memory conversion
BYTES_TO_MB = 1024 * 1024

# UUID and ID lengths
SESSION_ID_PREFIX_LENGTH = 8

# Buffer management
MIN_BUFFER_CHUNKS = 1
UTILIZATION_PERCENTAGE_BASE = 100

# Command completion timing
MAX_COMMAND_COMPLETION_WINDOW = 0.1

# Test constants
DEFAULT_TEST_TIMEOUT = 5.0
SMALL_TEST_TIMEOUT = 2.0
SHORT_TEST_TIMEOUT = 0.1
BENCHMARK_TIMEOUT = 10.0

# Test iteration counts
SMALL_ITERATION_COUNT = 3
MEDIUM_ITERATION_COUNT = 10
LARGE_ITERATION_COUNT = 100
STRESS_ITERATION_COUNT = 1000

# Performance thresholds
MIN_THROUGHPUT_MBPS = 10
MAX_SESSION_CREATION_TIME_MS = 50
MAX_SESSION_CREATION_TIME_S = 0.05
TARGET_CREATION_TIME_MS = 25
TARGET_CREATION_TIME_S = 0.025

# Memory thresholds
MEMORY_LEAK_THRESHOLD_MB = 50
MEMORY_GROWTH_MULTIPLIER = 2
MEMORY_CLEANUP_RATIO_THRESHOLD = 0.5
MEMORY_CLEANUP_SIGNIFICANT_THRESHOLD_MB = 0.1
MEMORY_LIMIT_TEST_MB = 500
LARGE_BUFFER_MEMORY_RELEASE_THRESHOLD_MB = -20

# Concurrency limits
CONCURRENT_SESSIONS_BENCHMARK = 25
CONCURRENT_SESSIONS_STRESS = 50
MAX_PERFORMANCE_CHUNKS = 150

# Timing windows
SMALL_DELAY_MS = 1
MEDIUM_DELAY_MS = 10
STANDARD_DELAY_MS = 100
LONG_DELAY_MS = 200

# Process management
PROCESS_WAIT_TIMEOUT = 5.0
PROCESS_SHUTDOWN_TIMEOUT = 2.0

# Buffer size limits
BUFFER_UTILIZATION_THRESHOLD = 0.7
LARGE_BUFFER_TEST_SIZE = 100 * 1024 * 1024  # 100MB

# Line numbers for testing
TEST_LINE_RANGE_START = 1
TEST_LINE_RANGE_END = 100
TEST_OUTPUT_VERIFICATION_LINES = [0, 1, 2]

# Command history limits
MAX_COMMAND_HISTORY_DISPLAY = 5

# Default encoding
DEFAULT_ENCODING = "utf-8"
ENCODING_ERROR_HANDLING = "ignore"
