name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried... but...

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area does this feature relate to?
      options:
        - Interactive sessions
        - Timing analysis
        - Report visualization
        - ORFS integration
        - MCP client support
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a concrete use case for this feature
      placeholder: |
        As a chip designer, I want to...
        So that I can...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
      placeholder: |
        - Similar features in other tools
        - Mock-ups or examples
        - Related issues or discussions

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I'd be willing to implement this feature
        - label: I'd be willing to test this feature
        - label: I'd be willing to write documentation for this feature
