name: Question
description: Ask a question about using OpenROAD MCP
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

        Before submitting, please check:
        - [README.md](https://github.com/The-OpenROAD-Project/openroad-mcp/blob/main/README.md) - Installation and basic usage
        - [QUICKSTART.md](https://github.com/The-OpenROAD-Project/openroad-mcp/blob/main/QUICKSTART.md) - Getting started guide
        - [FAQ](https://github.com/The-OpenROAD-Project/openroad-mcp/blob/main/README.md#faq) - Frequently asked questions
        - [Existing Issues](https://github.com/The-OpenROAD-Project/openroad-mcp/issues) - Someone may have already asked!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: dropdown
    id: question-category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation/Setup
        - Usage/How-to
        - Troubleshooting
        - Performance
        - Architecture/Design
        - Integration with other tools
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Provide any relevant context:
        - What are you trying to accomplish?
        - What have you already tried?
        - Your environment (OS, MCP client, etc.)
      placeholder: |
        I'm trying to...
        I've already looked at...

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any code snippets, error messages, or screenshots that might help
      placeholder: |
        ```
        Paste code or logs here
        ```
