name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: |
        make sync

    - name: Run formatting checks
      run: |
        make check

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t openroad-mcp:test .

    - name: Run tests in Docker container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -w /app \
          openroad-mcp:test \
          uv run pytest
      env:
        # Set high timeouts for MCP server tests
        MCP_SERVER_REQUEST_TIMEOUT: 99999999999
        MCP_REQUEST_MAX_TOTAL_TIMEOUT: 99999999999
