name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'

env:
  MCP_SERVER_REQUEST_TIMEOUT: 120
  MCP_REQUEST_MAX_TOTAL_TIMEOUT: 300

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        test-type: [lint, core, interactive, integration, tools]

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
    - run: make sync

    - name: Run lint
      if: matrix.test-type == 'lint'
      run: make check

    - name: Run core tests
      if: matrix.test-type == 'core'
      run: make test

    - name: Run interactive tests
      if: matrix.test-type == 'interactive'
      run: make test-interactive

    - name: Run integration tests
      if: matrix.test-type == 'integration'
      run: make test-integration

    - name: Run tools tests
      if: matrix.test-type == 'tools'
      run: make test-tools

  nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.event_name == 'schedule' || github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
    - run: make sync
    - run: make test-performance

  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
    - run: make sync
    - run: make test-coverage
    - uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
